import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html>
            <body>
                <h1><a href="">NEXTJS CRUD</a></h1>
                <div style={{display: 'flex'}}>
                <div style={{flex: 1}}>
                    <p>FROM SPRING BOOT</p>
                    CREATE
                    <li><input type="text" placeholder="name"/><input type="text" placeholder="amount"/><Link href="/create">Create</Link></li>
                    <br/>READ
                    <li><input type="text" placeholder="name"/><Link href="/read/1"><input type="button" value="readone"/></Link></li>
                    <li><Link href="/readall"><input type="button" value="readall"/></Link></li>
                    <br/>UPDATE
                    <li><input type="text" placeholder="name"/><input type="text" placeholder="amount"/><Link href="/update">Update</Link></li>
                    <br/>DELETE
                    <li><input type="text" placeholder="name"/><Link href="/delete"><input type="button" value="delete"/></Link></li>
                </div>
                <div style={{flex: 2}}>
                    {children}
                </div>
                </div>
            </body>
        </html>
    )
}
